### ISSUE TITLE
请问博主，你的个人主页（an.sheng.me）与博客页面(blog.ansheng.me)是两个域名还是？？

### ISSUE THREAD

**Issue by anydays** [anshengme/blog#10]
请问博主，你的个人主页（an.sheng.me）与博客页面(blog.ansheng.me)是两个域名还是？？还是用一个域名在哪设置的呢？还有就是Cloudflare免费CDN与SSL 在阿里云域名设置好了大概要多久生效呢？按照你blog教程设置好后等了几天没生效，后来还是切换了阿里云DNS!求解，谢谢！

**Comment by anshengme** [comment]
个人主页和博客是同一个有用吗，个人主页的页面是放在服务器上面的，博客是github pages+阿里云CDN

**Comment by anydays** [comment]
明白！请问下，你的博客github pages SSL也是阿里云的服务是吧？

**Comment by anshengme** [comment]
SSL用的阿里云CDN
